name: CI Pipeline
on: [push]
jobs:
  test-e2e:
    name: Install, Build, & Test E2E
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install, Build, Test E2E
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
  deploy-sdk:
    name: Deploy JS/TS SDK
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Build JS/TS SDK
        run: yarn build:sdk
      - name: Publish JS/TS SDK
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
