name: CI Pipeline
on: [push]
jobs:
  test-e2e:
    name: Build, Test, Deploy.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Build and Test
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
      - name: Build JS/TS SDK
        run: yarn build:sdk
      - name: NPM Config
        run: npm whoami && npm config ls -l
      - name: Publish JS/TS SDK
        run: npm publish ./dist/sdk --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
